### ISSUE TITLE
关于使用sdk订阅出现的问题

### ISSUE THREAD

**Issue by BingDaXian** [HuobiRDCenter/huobi_Java#13]
![image](https://user-images.githubusercontent.com/49145629/57896937-bdb12f00-7885-11e9-9b0a-7373045fe250.png)
![image](https://user-images.githubusercontent.com/49145629/57896949-cbff4b00-7885-11e9-9e14-cb3070949d31.png)
当把深度放在第一位订阅时候。深度推送正常、最新成交推送不正常。
![image](https://user-images.githubusercontent.com/49145629/57896970-e802ec80-7885-11e9-809f-dcc2a47ed8e9.png)
![image](https://user-images.githubusercontent.com/49145629/57896973-ed603700-7885-11e9-9561-3114d3d88a8f.png)
更换顺序以后最新成交推送正常。深度推送不正常。、
不知道是有什么sdk订阅的规则限制吗。

**Comment by macomfan** [comment]
SDK这边没有限制，建议你把两个symbol做成一个字符串传进去再试试，比如subscriptionClient.subscribeTradeEvent(“eosbtc,eosusdt”, ....)
