### ISSUE TITLE
com.hbdm.client.impl.WebSocketConnection重连的时候可能出现多次重连的情况

### ISSUE THREAD

**Issue by shmilyLT** [HuobiRDCenter/huobi_Java#15]
WebSocketWatchDog重连逻辑中，如果WebSocketConnection的连接状态为DELAY_CONNECT的时候，可能引发多次重连，建议在WebSocketConnection的connect方法中重置状态值，此方法复现可以在WebSocket连接成功后断开2分钟以上的网络，再次重连，可发现重连的数量超过1个。
![image](https://user-images.githubusercontent.com/24970417/59419864-652a6e80-8dfe-11e9-8fe3-bc01dc70fc69.png)

**Comment by myarth** [comment]
嗯，在 webSocket = RestApiInvoker.createWebSocket(okhttpRequest, this); 后，如果 1s 内（watchDog 间隔时间）webSocket.onOpen 没有及时更新 state 的状态的话，就会出现；但这种场景如果 onOpen 没有被调用，webSocket 应该就创建失败了，后续再次调用也没问题；

**Comment by myarth** [comment]
这样处理确实可以解决在网络状况不好的情况下会出现多个连接的场景；

这段日志也说明了，当 17:58:41,419 WatchDog 尝试去获取新的连接，但在下1s 17:58:42,419 前 com.huobi.client.impl.RestApiInvoker#createWebSocket 没能 com.huobi.client.impl.WebSocketConnection#onOpen 更新 state = ConnectionState.CONNECTED; 由于网络情况不佳也没能发生异常 com.huobi.client.impl.WebSocketConnection#onFailure 更新 state = ConnectionState.CLOSED_ON_ERROR;
导致该次也发生了重连；

`17:58:25,419 [pool-1-thread-1] WARN  c.h.client.impl.WebSocketConnection     - [Sub][0] Reconnecting after 15 seconds later`
`17:58:41,419 [pool-1-thread-1] INFO  c.h.client.impl.WebSocketConnection     - [Sub][0] Connecting...`
`17:58:42,419 [pool-1-thread-1] INFO  c.h.client.impl.WebSocketConnection     - [Sub][0] Connecting...`

**Comment by YXQ212526** [comment]
sdk 已更新至v2版本
