### ISSUE TITLE
API withdrawal does not support temporary addresses

### ISSUE THREAD

**Issue by lijianl** [HuobiRDCenter/huobi_Java#16]
ERROR: API withdrawal does not support temporary addresses  
currency:ada

**Comment by macomfan** [comment]
Could you pls provide the detail information, which interface did you call? and what parameters did you pass?

**Comment by huobiapi** [comment]
@lijianl For security purpose, you need to add the address into the pre-defined address table on Huobi official website before withdrawing through API.

**Comment by valeriov382** [comment]
Hello,
  when using APIs I am getting this error even if I try to withdraw to an address registered in the whitelist. I get this problem for all whitelisted addresses that I have tried.
b'{"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}'

I can withdraw to that address from the website without 2 factor autentication so the websiste correctly treat it as a whitelisted address.

What can I do to create withdrawals via API ?

Any help is appreciated thanks!

**Comment by dzaan-mshia** [comment]
having same porblem
