### ISSUE TITLE
你好，文档中描述的HuobiClientFactory这个类找不到，请问是不是更名了，文档没有更新？

### ISSUE THREAD

**Issue by leguang** [HuobiRDCenter/huobi_Java#17]
你好，文档中描述的HuobiClientFactory这个类找不到，请问是不是更名了，文档没有更新？

**Comment by macomfan** [comment]
这个是文档没有更新，稍后会修正，你可以使用下面的代码得到SubscriptionClient
SubscriptionClient subscriptionClient = SubscriptionClient.create();
