### ISSUE TITLE
你好，请问如何实时监听某个交易对的当前最新价格？非常感谢

### ISSUE THREAD

**Issue by leguang** [HuobiRDCenter/huobi_Java#18]
你好，请问如何实时监听某个交易对的当前最新价格？非常感谢
就比如我想实时监听BTC/USDT的当前最新价格，该怎么做？

**Comment by macomfan** [comment]
可以通过订阅接口subscribeTradeEvent，具体可参考Readme

**Comment by heng5120** [comment]
最近我使用这个接口获取的价格偶尔会出现跳价的情况，就是高于或低于这个时间段K线的最高或者最低价，导致价格不准确，请问有碰到类似问题吗

> 可以通过订阅接口subscribeTradeEvent，具体可参考Readme
