### ISSUE TITLE
can't reconnect if there are VPN issues (solved - patch applied)

### ISSUE THREAD

**Issue by kruchinin-pavel** [HuobiRDCenter/huobi_Java#39]
In some cases, the VPN connection can make outgoing connection deaf (no messages from web socket). Thus watchdog constantly tries to create WebSockets more and more without closing existing ones.

**Comment by kruchinin-pavel** [comment]
I have fixed it in my fork of current repo, and hope you can take this fix.

[fix_issues_with_reconnect.patch.txt](https://github.com/HuobiRDCenter/huobi_Java/files/4005885/fix_issues_with_reconnect.patch.txt)

**Comment by kruchinin-pavel** [comment]
would be happy to join your repo as a participant

**Comment by eynzhang** [comment]
@kruchinin-pavel thanks for the contribution, would you mind creating a pull request on Github? It will be easier to review and track the code change.

**Comment by kruchinin-pavel** [comment]
> @kruchinin-pavel thanks for the contribution, would you mind creating a pull request on Github? It will be easier to review and track the code change.

I wished I would
![image](https://user-images.githubusercontent.com/5062078/79943687-35161800-8472-11ea-871f-e1651e2aa92f.png)

**Comment by eynzhang** [comment]
@kruchinin-pavel you shouldn’t create a branch on this repository directly, the suggest steps in Github are:
1.  You fork a new repository as yours
2. You make changes in your forked repository
3. Create a pull request from your forked repository to source repository.

**Comment by kruchinin-pavel** [comment]
PR created. Please take a look.

**Comment by eynzhang** [comment]
Thanks for your contribution, we have upgraded to version 2 and you can try that.
