### ISSUE TITLE
Verification Failure when create futures contract

### ISSUE THREAD

**Issue by lamtrhieu** [HuobiRDCenter/huobi_Java#43]
I follow the authentication request guide to create request and place order via "POST api/v1/contract_order"
The request url is `request_url: "https://api.hbdm.com/api/v1/contract_order?AccessKeyId=3c8dd81a-d8b5e97e-qv2d5ctgbn-9bd14&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2020-03-09T10%3A46%3A21&Signature=/4tZI8AHjF8tdpyB+j5RMOA7/E91bOItkq17wqoOgtI=",
`
The body is `body: "{\"contract_type\":\"this_week\",\"direction\":\"Buy\",\"lever_rate\":5,\"offset\":\"open\",\"order_price_type\":\"limit\",\"price\":5000,\"symbol\":\"BTC\",\"volume\":1}",`

But I intermittently run into `%{
   "err_code" => 403,
   "err_msg" => "Verification failure [校验失败]",
   "status" => "error",
   "ts" => 1583750781573
 }` 
It fails for about 3,4 request, and then the next request succeeded. 
Why is it so unstable ? How can I improve it ?

**Comment by eynzhang** [comment]
@lamtrhieu thanks for raising your issues. Your issue is about future API not spot API, our colleagues have contacted you in separate channel. We will close this issue in GitHub.

**Comment by normanlmfung** [comment]
I have same issue, but with python (Dont think it matters)
https://github.com/HuobiRDCenter/huobi_Python/issues/126

**Comment by marcinrabiej** [comment]
Hi, we keep having exactly same problem: error code 403, Verification failure [校验失败]. Approximately 11% of our new order requests are failing with this issue. Has anyone resolved it? @eynzhang can you please put me in contact with your colleagues working on futures API?
