### ISSUE TITLE
I can't find api about user-center/orders/

### ISSUE THREAD

**Issue by FishInJava** [HuobiRDCenter/huobi_Java#45]
你好，找不到user-center/orders/相关的api，我想查询法币交易订单，比如btc和CNY交易的订单，请问只能自己发送http请求吗？
浏览器上的请求需要fingerprint，trace_id，token等参数，每次需要登陆后，才能在cookies中看到。。。能给我一个用私钥参考吗?感谢了

**Comment by huobidqx** [comment]
您好，关于OTC我们暂未提供官方的API接口，我们不建议您使用爬虫的方式爬取web端访问接口，也无法为您提供相关私钥信息

**Comment by FishInJava** [comment]
好的，感谢回答
