### ISSUE TITLE
有没有永续合约和交割合约SDK呢

### ISSUE THREAD

**Issue by zhouzhi91** [HuobiRDCenter/huobi_Java#55]
我在使用SDK时，发现并没有关于永续合约和交割合约这两个相关的SDK，只有对现货的SDK，有没有关系永续合约和交割合约的SDK呢 ，如果有，请提供地址。

**Comment by eynzhang** [comment]
@zhouzhi91 合约的SDK可以从文档上找到相关地址：
交割合约：https://huobiapi.github.io/docs/dm/v1/cn/#2cff7db524
永续合约：https://huobiapi.github.io/docs/coin_margined_swap/v1/cn/#2cff7db524
