### ISSUE TITLE
v2是还不能用吧

### ISSUE THREAD

**Issue by panzhoutao** [HuobiRDCenter/huobi_Java#57]
demo里并不能使用

**Comment by eynzhang** [comment]
v2已经可以使用了，本周合并到了master分支。样例代码在src/test/java/com/huobi/examples
具体的设计可以参加README。

您具体遇到了什么问题？

**Comment by panzhoutao** [comment]
> v2=，[大师][src/test/java/com/huobi/
> 示例][README]
> 
> 您具体遇到了什么问题?

HuobiOptions.builder() 像这样的builder都找不到
