### ISSUE TITLE
ws订阅accounts，同时订阅 可用和total，返回的数据没有字段可以区分

### ISSUE THREAD

**Issue by myarth** [HuobiRDCenter/huobi_Java#6]
model | string | 选填；订阅账户balance类型。0 代表可用，即type=trade的balance; 1 代表 total，即该账户的总余额，包括type=trade 和type=frozen的余额的和。当mode缺省时，默认值为0.
-- | -- | --

发起两个订阅，0 和 1的，当币币交易成功，账户发生变化时，每个订阅各收到一条消息，格式如下：{"changeType":"TRADE","data":[{"accountType":"SPOT","balance":,"balanceType":"TRADE","currency":"usdt"}],"timestamp":}

除了 balance 字段值不同以外（对应可用和total），没有字段可以区分。

**Comment by huobiapi** [comment]
@myarth 感谢您的反馈，我们已推出v2版本账户订阅接口，账户余额和可用余额分别有两字段。
详见：https://huobiapi.github.io/docs/spot/v1/cn/#f2e38456dd
