### ISSUE TITLE
com.huobi.client.impl.utils.TimeService#convertCSTInMillisecondToUTC 服务端返回的 long 已经是UTC

### ISSUE THREAD

**Issue by myarth** [HuobiRDCenter/huobi_Java#8]
com.huobi.client.impl.utils.TimeService#convertCSTInMillisecondToUTC

服务端返回的 long timeInMs 已经是 GMT 的，建议在转 Date 或 Instant 时处理时区；此处强减只保证东八区的程序 new Date(convert...()) 是正确的 UTC 时间； 

public static long convertCSTInMillisecondToUTC(long timeInMs) {
    if (timeInMs > 946656000000L) {
      // bigger than 2000-01-01 00:00:00
      return timeInMs - 8 * 60 * 60 * 1000; // 此处减8小时，只对东八区的 new Date(convert...()) 才表达出转 UTC 的含义； 
    }
    return 0;
  }

**Comment by myarth** [comment]
public static void main(String[] args) {
    System.out.println(new Date(0).toLocaleString());
  }

**Comment by macomfan** [comment]
这个需要和API维护人员确认，如果API通过JSON返回的的已经是UTC时间，这个转换需要去掉
